apiVersion: 1

datasources:
  - name: prometheus
    uid: prom
    orgId: 1
    type: prometheus
    typename: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://10.114.0.3:8080/
    database: ''
    user: ''
    basicAuth: false
    jsonData:
      httpMethod: POST
      oauthPassThru: false
      sigV4Auth: false
    isDefault: true
    readonly: false

  - name: Loki
    type: loki
    typeName: Loki
    orgId: 1
    uid: log-loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    access: proxy
    url: http://192.168.1.5:3100
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    readonly: false
