version: '3.5'

networks:
  main:
    name: minitwit-network

volumes:
  pgdata:


services:

  minitwit-frontend:
    image: ghcr.io/devops2024-group-e/frontend.minitwit:latest
    container_name: frontend
    networks:
      - main
    depends_on:
      - minitwit-db
    ports:
      - '80:80'

  minitwit-backend:
    image: ghcr.io/devops2024-group-e/backend.minitwit:latest
    container_name: backend
    networks:
      - main
    depends_on:
      - minitwit-db
    ports:
      - '8080:8080'

  minitwit-db:
    image: ghcr.io/devops2024-group-e/database.minitwit:latest
    container_name: database
    networks:
      - main
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - main
