version: 2
updates:
    # Maintain dependencies for Github Actions
    - package-ecosystem: "github-action"
      directory: "/"
      schedule:
        interval: "daily"
    
    # Maintain dependencies for Nuget / .NET packages
    - package-ecosystem: "nuget"
      directory: "/"
      schedule:
        interval: "daily"