version: 2
updates:
    # Maintain dependencies for Github Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "daily"

    # Maintain dependencies for Nuget / .NET packages
    - package-ecosystem: "nuget"
      directory: "/"
      schedule:
        interval: "daily"

    # Maintain dependencies for Docker
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
        interval: "daily"
    
    # Maintain dependencies for devcontainer
    - package-ecosystem: "devcontainers"
      directory: "/"
      schedule:
        interval: "daily"