# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
    -   id: hadolint
-   repo: https://github.com/dotnet/format
    rev: "v8.0.453106"
    hooks:
    -   id: dotnet-format
