FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build


WORKDIR /src
COPY . ./
WORKDIR /src/Minitwit
RUN dotnet build -c release && dotnet publish -c release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
ARG DB_CONN=""

ENV ASPNETCORE_URLS=http://*:80/

WORKDIR /src
COPY --from=build /src/Minitwit/out .

EXPOSE 80

ENV Minitwit_ConnectionStrings__MinitwitDatabase=${DB_CONN}

ENTRYPOINT [ "./Minitwit" ]
