FROM postgres:16

ARG USER_PWD="123"

ENV POSTGRES_USER=minitwit-sa
ENV POSTGRES_PASSWORD=${USER_PWD}
ENV POSTGRES_DB=minitwit

WORKDIR /db-setup
COPY . /db-setup
COPY schema.sql /docker-entrypoint-initdb.d
