---
- name: Standard Deny all
  community.general.ufw:
    policy: deny

- name: Allow port 80 for HTTP
  community.general.ufw:
    rule: allow
    port: '80'

- name: Allow port 8080 for HTTP
  community.general.ufw:
    rule: allow
    port: '8080'

- name: Allow SSH
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '22'

- name: Exposing loki port
  community.general.ufw:
    rule: allow
    direction: in
    interface: eth1
    port: '3100'

- name: Enable firewall
  community.general.ufw:
    state: enabled
