---
# tasks file for roles/swarm
- name: check/init swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ groups['swmmanagers'][0]['eth1']['ipv4']['address']}}:2377"
  register: __output_swarm
  when: inventory_hostname in groups['swmmanagers'][0]

- name: install manager
  community.docker.docker_swarm:
    state: join
    timeout: 60
    advertise_addr: eth1:2377
    join_token: "{{ hostvars[groups['swmmanagers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Manager']}}"
    remote_addrs: "{{ groups['swmmanager'][0]['eth1']['ipv4']['address']}}"
  when: inventory_hostname in groups['swmmanagers'] and inventory_hostname not in groups['swmmanagers'][0]

- name: install worker
  community.docker.docker_swarm:
    state: join
    timeout: 60
    advertise_addr: eth1:2377
    join_token: "{{ hostvars[groups['swmmanagers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ hostvars[groups['swmmanagers'][0]]['eth1']['ipv4']['address'] }}"
  when: inventory_hostname in groups['swmnodes']

- name: Add bashrc path to bash_profile
  ansible.builtin.shell: echo ". /root/.bashrc" > ~/.bash_profile

- name: Set bash_profile to source
  ansible.builtin.shell: source ~/.bash_profile
  args:
    executable: /bin/bash

- name: Set /minitwit as home dir
  ansible.builtin.shell: echo "cd /minitwit" >> ~/.bash_profile

- name: Synchronization of configuration files from web-server to server minitwit dir
  ansible.posix.synchronize:
    src: swm-man-server/
    dest: /minitwit
    checksum: true
  when: inventory_hostname in groups['swmmanagers']
