---
# tasks file for roles/swarm
- name: check/init swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ groups['swmmanagers'][0] }}:2377"
  register: __output_swarm
  when: inventory_hostname in groups['swmmanagers'][0]

- name: install manager
  community.docker.docker_swarm:
    state: join
    timeout: 60
    advertise_addr: eth0:2377
    join_token: "{{ hostvars[groups['swmmanagers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Manager']}}"
    remote_addrs: "{{ groups['swmmanager'][0] }}"
  when: inventory_hostname in groups['swmmanagers'] and inventory_hostname not in groups['swmmanagers'][0]

- name: install worker
  community.docker.docker_swarm:
    state: join
    timeout: 60
    advertise_addr: eth0:2377
    join_token: "{{ hostvars[groups['swmmanagers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ groups['swmmanagers'][0] }}"
  when: inventory_hostname in groups['swmnodes']
