version: '3.5'

networks:
  main:
    name: minitwit-network

services:

  minitwit-frontend:
    image: ghcr.io/devops2024-group-e/frontend.minitwit:latest
    container_name: frontend
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: stop-first
    networks:
      - main
    depends_on:
      - minitwit-db
    ports:
      - '80:80'
    logging:
      driver: loki
      options:
        loki-url: http://64.227.124.243:3100/loki/api/v1/push # TODO: Change this to the private URL of the ops-1 server
    environment:
      - Minitwit_ConnectionStrings__MinitwitDatabase=Host=private-minitwit-test-db-01-4158eeb-do-user-15947112-0.c.db.ondigitalocean.com;Port=25060;Username=minitwit-sa;Password=***;Database=minitwit
    labels:
      - prometheus-job=minitwit-frontend

  minitwit-backend:
    image: ghcr.io/devops2024-group-e/backend.minitwit:latest
    container_name: backend
    deploy:
      replicas: 2
      update_config:
        delay: 10s
        order: stop-first
    networks:
      - main
    logging:
      driver: loki
      options:
        loki-url: http://64.227.124.243:3100/loki/api/v1/push # TODO: Change this to the private URL of the ops-1 server
    ports:
      - '8080:8080'
    labels:
      - prometheus-job=minitwit-api

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: stop-first
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - main
