version: '3.5'

networks:
  main:
    name: minitwit-dev-network

services:
  dotnet-dev:
    image: mcr.microsoft.com/devcontainers/dotnet:7.0
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cachedd
    networks:
      - main
    depends_on:
      - minitwit-db

  minitwit-db:
    build:
      context: ./..
      dockerfile: Dockerfile.database
    container_name: minitwit-dev-database
    networks:
      - main
    ports:
      - '5432:5432'
