version: '3.5'

networks:
  main:
    name: minitwit-dev-network

services:
  dotnet-dev:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ../:/workspace
    command: sleep infinity
    networks:
      - main
    environment:
      - Minitwit_ConnectionStrings__MinitwitDatabase=Host=minitwit-dev-database;Port=5432;Username=minitwit-sa;Password=123;Database=minitwit
      - Minitwit_ConnectionStrings__Redis=minitwit-cache:6379

  minitwit-db:
    build:
      context: ./..
      dockerfile: Dockerfile.database
    container_name: minitwit-dev-database
    networks:
      - main
    ports:
      - '5432:5432'

  cache:
    image: redis:7.2.4
    container_name: minitwit-cache
    networks:
      - main
    ports:
      - '6379:6379'
