version: '3.5'

networks:
  main:
    name: minitwit-network
    driver: overlay

services:

  minitwit-frontend:
    image: ghcr.io/devops2024-group-e/frontend.minitwit:latest
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: stop-first
    networks:
      - main
    depends_on:
      - minitwit-db
    ports:
      - '80:80'
    logging:
      driver: loki
      options:
        loki-url: http://192.168.1.5:3100/loki/api/v1/push
    labels:
      - prometheus-job=minitwit-frontend

  minitwit-backend:
    image: ghcr.io/devops2024-group-e/backend.minitwit:latest
    deploy:
      replicas: 2
      update_config:
        delay: 10s
        order: stop-first
    networks:
      - main
    logging:
      driver: loki
      options:
        loki-url: http://192.168.1.5:3100/loki/api/v1/push
    ports:
      - '8080:8080'
    labels:
      - prometheus-job=minitwit-api

  prometheus:
    image: prom/prometheus
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: stop-first
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9090:9090'
    networks:
      - main
