name: Build latex report

on:
  workflow_dispatch:
    manual: true
  push:
    branches:
      - main
    paths:
      report/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Build latex document and commit
        run: |
          echo "Building report"
          cd report
          sh ./scripts/compile-latex-docker.sh main.tex
          # Run it twice to ensure the correct aux files are used
          sh ./scripts/compile-latex-docker.sh main.tex

          echo "Commit and push report"
          git config user.name "anti-itu"
          git config user.email "anti@itu.dk"
          git add -A
          git commit -m "Build LaTeX [skip ci]"
          git push

      # - name: Changelog
      #   uses: scottbrenner/generate-changelog-action@master
      #   id: Changelog
      #   env:
      #     REPO: ${{ github.repository }}

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: Report-v${{ steps.bump.outputs.newVersion }}
      #     release_name: Report v${{ steps.bump.outputs.newVersion }}
      #     body: |
      #       ${{ steps.Changelog.outputs.changelog }}
      #     draft: false
      #     prerelease: false
