name: Linting and formatting check

on:
  workflow_dispatch:
    manual: true
  pull_request:


jobs:
  Pre-commit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: install hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
