---
name: provision-and-deployment
run-name: Provision infrastructure and deploy application

on:
  workflow_dispatch:
    manual: true

jobs:
  provision-web:
    name: Provision and deploy web servers
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Fetch Ansible Playbook action
        uses: actions/checkout@v4
        with:
          repository: devops2024-group-e/ansible-action
          sparse-checkout: |
            .github/actions/ansible-run-playbook
          sparse-checkout-cone-mode: false
          path: action

      - name: Provision and deploy web servers
        uses: ./action/.github/actions/ansible-run-playbook
        with:
          dotoken: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          dosshkeyname: ${{ secrets.DIGITAL_OCEAN_ANSIBLE_SSH_KEY_NAME }}
          sshkey: ${{ secrets.ANSIBLE_SSH_KEY }}
          dockeruser: ${{ secrets.DOCKER_USER }}
          dockerpassword: ${{ secrets.DOCKER_PWD }}
          inventoryfile: inventory.ansible
          playbook: web-playbook.yaml
          working-directory: main/.infrastructure

  provision-monitor:
    name: Provision and deploy monitor server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Fetch Ansible Playbook action
        uses: actions/checkout@v4
        with:
          repository: devops2024-group-e/ansible-action
          sparse-checkout: |
            .github/actions/ansible-run-playbook
          sparse-checkout-cone-mode: false
          path: action

      - name: Provision and deploy monitoring servers
        uses: ./action/.github/actions/ansible-run-playbook
        with:
          dotoken: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          dosshkeyname: ${{ secrets.DIGITAL_OCEAN_ANSIBLE_SSH_KEY_NAME }}
          sshkey: ${{ secrets.ANSIBLE_SSH_KEY }}
          dockeruser: ${{ secrets.DOCKER_USER }}
          dockerpassword: ${{ secrets.DOCKER_PWD }}
          inventoryfile: inventory.ansible
          playbook: monitor-playbook.yaml
          working-directory: main/.infrastructure
