name: Testing

on:
  workflow_dispatch:
    manual: true
  pull_request:
    paths:
      - 'Minitwit/**'
      - 'Minitwit.Tests/**'
      - 'MinitwitSimulatorAPI/**'
      - 'Minitwit.Simulator.Api.Tests/**'
      - 'Minitwit.Infrastructure/**'
      - 'Minitwit.Infrastructure.Tests/**'

jobs:
  Pre-commit-check:
    runs-on: ubuntu-latest

    steps:
      - name: install hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  Minitwit-Infrastructure-Tests:
    runs-on: ubuntu-latest
    needs: Pre-commit-check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dotnet dependencies
        run: dotnet restore

      - name: Test dotnet version
        run: dotnet --version

      - name: Test
        run: dotnet test Minitwit.Infrastructure.Tests/Minitwit.Infrastructure.Tests.csproj

  Backend-Tests:
    runs-on: ubuntu-latest
    needs: Pre-commit-check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dotnet dependencies
        run: dotnet restore

      - name: Test dotnet version
        run: dotnet --version

      - name: Set up database
        run: docker compose -f docker-compose.yaml up minitwit-db -d

      - name: Test
        run: dotnet test Minitwit.Simulator.Api.Tests/Minitwit.Simulator.Api.Tests.csproj

  Frontend-Tests:
    runs-on: ubuntu-latest
    needs: Pre-commit-check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dotnet dependencies
        run: dotnet restore

      - name: Test dotnet version
        run: dotnet --version

      - name: Set up database
        run: docker compose -f docker-compose.yaml up minitwit-db -d

      - name: Test
        run: dotnet test Minitwit.Tests/Minitwit.Tests.csproj
