---
name: Testing

on:
#  pull_request:
#    types: opened
#    branches:
#      - 'feature/**'
#    paths:
#      - 'Minitwit/**'
#      - 'MinitwitSimulatorAPI/**'
  # allow manual triggers for now tooo
  workflow_dispatch:
    manual: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          echo "Installing pip ==="
          python -m pip install --upgrade pip
          echo "Installing dependences ==="
          echo "$PWD"
          pip install -r requirements.txt
        
      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dotnet dependencies
        run: dotnet restore
      
      - name: Test versions
        run: |
          python --version
          dotnet --version
#      - name: Test Minitwit Endpoints
#        run: | 
#          docker compose -f docker-compose.yaml up minitwit-db
          # cd MinitwitSimulatorAPI
          # dotnet run
          # pytest minitwit_sim_api_test.py
#          docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile-minitwit-tests .
#          yes 2>/dev/null | docker-compose up -d
#          docker run --rm --network=itu-minitwit-network $DOCKER_USERNAME/minitwittestimage
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
