---
name: Testing

on:
  workflow_dispatch:
    manual: true
  pull_request:
    paths:
      - 'Minitwit/**'
      - 'Minitwit.Tests/**'
      - 'MinitwitSimulatorAPI/**'
      - 'Minitwit.Simulator.Api.Tests/**'
  
jobs:
  IntegrationTests-LoginAndLogout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dotnet dependencies
        run: dotnet restore
      
      - name: Test dotnet version
        run: dotnet --version
     
      - name: Set up database
        run: docker compose -f docker-compose.yaml up minitwit-db -d
      
      - name: Test
        run: dotnet test Minitwit.Tests/Minitwit.Tests.csproj --filter FullyQualifiedName~Minitwit.Tests.IntegrationTests.LoginAndLogoutTests
        
  IntegrationTests-Register:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dotnet dependencies
        run: dotnet restore
      
      - name: Test dotnet version
        run: dotnet --version
     
      - name: Set up database
        run: docker compose -f docker-compose.yaml up minitwit-db -d
      
      - name: Test
        run: dotnet test Minitwit.Tests/Minitwit.Tests.csproj --filter FullyQualifiedName~Minitwit.Tests.IntegrationTests.RegisterTests

  IntegrationTests-Timeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dotnet dependencies
        run: dotnet restore
      
      - name: Test dotnet version
        run: dotnet --version
     
      - name: Set up database
        run: docker compose -f docker-compose.yaml up minitwit-db -d
      
      - name: Test
        run: dotnet test Minitwit.Tests/Minitwit.Tests.csproj --filter FullyQualifiedName~Minitwit.Tests.IntegrationTests.TimelineTests
