global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'minitwit-app-docker'

    scrape_interval: 10s

    static_configs:
      - targets: ['10.114.0.2:9323']
        labels:
          group: 'production'

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['10.114.0.3:8080']

  - job_name:       'minitwit-frontend'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['10.114.0.2:80']
        labels:
          group: 'production'

  - job_name:       'minitwit-backend'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['10.114.0.2:8080']
        labels:
          group: 'production'
